sonar.projectKey=Los-Ingenieros-Del-Prompt_Lobby_Azar_Cafetero
sonar.organization=los-ingenieros-del-prompt
sonar.projectName=Azar Cafetero - Lobby Service
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.sourceEncoding=UTF-8
sonar.java.source=21

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones de cobertura — EXACTAMENTE iguales a las de JaCoCo en pom.xml
sonar.coverage.exclusions=\
  **/LobbyApplication.java,\
  **/infrastructure/persistence/entity/**,\
  **/infrastructure/persistence/repository/**,\
  **/infrastructure/persistence/adapter/**,\
  **/infrastructure/config/**,\
  **/infrastructure/security/**,\
  **/infrastructure/sse/**,\
  **/infrastructure/web/GameTransactionRequest.java

sonar.exclusions=**/target/**
